// GENERATED by scripts/import-tiles.ts from seed-data/source/tiles_details.xlsx.
// Do not edit by hand — change the spreadsheet (or TILE_COPY) and re-run:
//   npx tsx scripts/import-tiles.ts
import type { Category, Product } from "./types";

export const tileCategories: Category[] = [
  {
    "slug": "floor-tiles",
    "vertical": "ceramic-tiles",
    "name": "Floor Tiles",
    "tagline": "Floors for every room, from classic squares to large-format slabs.",
    "description": "Floor tiles for living rooms, bedrooms, lobbies and commercial spaces. Available in 4 series, in 6 sizes from 600×600 to 1200×2400 mm.",
    "filters": [
      {
        "label": "Series",
        "options": [
          "Series A",
          "Series B",
          "Series C",
          "Series D"
        ]
      },
      {
        "label": "Size",
        "options": [
          "600×600 mm",
          "600×1200 mm",
          "800×1600 mm",
          "1200×1200 mm",
          "800×2400 mm",
          "1200×2400 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "wall-tiles",
    "vertical": "ceramic-tiles",
    "name": "Wall Tiles",
    "tagline": "Walls with texture, tone and character.",
    "description": "Wall tiles for feature walls, living spaces and everyday interiors. Available in 2 series, in 4 sizes from 300×450 to 600×1200 mm.",
    "filters": [
      {
        "label": "Series",
        "options": [
          "Series A",
          "Series B"
        ]
      },
      {
        "label": "Size",
        "options": [
          "300×450 mm",
          "300×600 mm",
          "600×600 mm",
          "600×1200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "bathroom-tiles",
    "vertical": "ceramic-tiles",
    "name": "Bathroom Tiles",
    "tagline": "Tiles made for the bath, floor to ceiling.",
    "description": "Tiles for bathroom floors and walls, chosen for spaces that see water every day. Available in 3 series, in 4 sizes from 300×600 to 700×1200 mm.",
    "filters": [
      {
        "label": "Series",
        "options": [
          "Series A",
          "Series B",
          "Series C"
        ]
      },
      {
        "label": "Size",
        "options": [
          "300×600 mm",
          "600×600 mm",
          "600×1200 mm",
          "700×1200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "kitchen-tiles",
    "vertical": "ceramic-tiles",
    "name": "Kitchen Tiles",
    "tagline": "Surfaces for the heart of the home.",
    "description": "Tiles for kitchen walls, backsplashes and work areas that are easy to keep clean. Available in 2 series, in 4 sizes from 300×450 to 600×1200 mm.",
    "filters": [
      {
        "label": "Series",
        "options": [
          "Series A",
          "Series B"
        ]
      },
      {
        "label": "Size",
        "options": [
          "300×450 mm",
          "300×600 mm",
          "600×600 mm",
          "600×1200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "outdoor-tiles",
    "vertical": "ceramic-tiles",
    "name": "Outdoor Tiles",
    "tagline": "Built for terraces, pathways and open-air living.",
    "description": "Tiles for terraces, balconies, pathways and other outdoor areas. Available in 14 sizes from 300×450 to 1600×3200 mm.",
    "filters": [
      {
        "label": "Size",
        "options": [
          "300×450 mm",
          "300×500 mm",
          "400×400 mm",
          "300×600 mm",
          "700×300 mm",
          "600×600 mm",
          "800×800 mm",
          "600×1200 mm",
          "700×1200 mm",
          "800×1600 mm",
          "800×2000 mm",
          "800×2400 mm",
          "1700×1500 mm",
          "1600×3200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "ceramic-tiles",
    "vertical": "ceramic-tiles",
    "name": "Ceramic Tiles",
    "tagline": "Everyday ceramic, in sizes for every room.",
    "description": "Ceramic tiles for residential floors and walls. Available in 4 sizes from 400×400 to 600×1200 mm.",
    "filters": [
      {
        "label": "Size",
        "options": [
          "400×400 mm",
          "500×500 mm",
          "600×600 mm",
          "600×1200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "vitrified-tiles",
    "vertical": "ceramic-tiles",
    "name": "Vitrified Tiles",
    "tagline": "A clean, consistent finish for modern floors.",
    "description": "Vitrified tiles for floors in homes, offices and commercial spaces. Available in 4 sizes from 400×400 to 600×1200 mm.",
    "filters": [
      {
        "label": "Size",
        "options": [
          "400×400 mm",
          "500×500 mm",
          "600×600 mm",
          "600×1200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "dc-tiles",
    "vertical": "ceramic-tiles",
    "name": "D.C. Tiles",
    "tagline": "Double-charge tiles for floors that work hard.",
    "description": "D.C. (double-charge) tiles for floors in homes and busy commercial spaces. Available in 4 sizes from 400×400 to 600×1200 mm.",
    "filters": [
      {
        "label": "Size",
        "options": [
          "400×400 mm",
          "500×500 mm",
          "600×600 mm",
          "600×1200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "nano-tiles",
    "vertical": "ceramic-tiles",
    "name": "Nano Tiles",
    "tagline": "A polished look that stays on show.",
    "description": "Nano-finish tiles for floors in homes, showrooms and retail spaces. Available in 4 sizes from 400×400 to 600×1200 mm.",
    "filters": [
      {
        "label": "Size",
        "options": [
          "400×400 mm",
          "500×500 mm",
          "600×600 mm",
          "600×1200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  },
  {
    "slug": "parking-tiles",
    "vertical": "ceramic-tiles",
    "name": "Parking Tiles",
    "tagline": "Tough surfaces for driveways and parking.",
    "description": "Tiles for parking areas, driveways and other spaces that take vehicle traffic. Available in 4 sizes from 400×400 to 600×1200 mm.",
    "filters": [
      {
        "label": "Size",
        "options": [
          "400×400 mm",
          "500×500 mm",
          "600×600 mm",
          "600×1200 mm"
        ]
      }
    ],
    "syncOnSeed": true
  }
];

export const tileProducts: Product[] = [
  {
    "slug": "floor-tiles-series-a",
    "vertical": "ceramic-tiles",
    "categorySlug": "floor-tiles",
    "name": "Floor Tiles – Series A",
    "collection": "Series A",
    "shortDescription": "Floor Tiles, Series A, in 6 sizes from 600×600 to 1200×2400 mm.",
    "description": "Floor tiles for living rooms, bedrooms, lobbies and commercial spaces. Series A is offered in 6 sizes: 600×600 mm, 600×1200 mm, 800×1600 mm, 1200×1200 mm, 800×2400 mm, 1200×2400 mm.",
    "finishes": [],
    "sizes": [
      "600×600 mm",
      "600×1200 mm",
      "800×1600 mm",
      "1200×1200 mm",
      "800×2400 mm",
      "1200×2400 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Floor Tiles"
      },
      {
        "label": "Series",
        "value": "A"
      },
      {
        "label": "Sizes available",
        "value": "6"
      },
      {
        "label": "Size range",
        "value": "600×600 to 1200×2400 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "floor-tiles-series-b",
    "vertical": "ceramic-tiles",
    "categorySlug": "floor-tiles",
    "name": "Floor Tiles – Series B",
    "collection": "Series B",
    "shortDescription": "Floor Tiles, Series B, in 6 sizes from 600×600 to 1200×2400 mm.",
    "description": "Floor tiles for living rooms, bedrooms, lobbies and commercial spaces. Series B is offered in 6 sizes: 600×600 mm, 600×1200 mm, 800×1600 mm, 1200×1200 mm, 800×2400 mm, 1200×2400 mm.",
    "finishes": [],
    "sizes": [
      "600×600 mm",
      "600×1200 mm",
      "800×1600 mm",
      "1200×1200 mm",
      "800×2400 mm",
      "1200×2400 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Floor Tiles"
      },
      {
        "label": "Series",
        "value": "B"
      },
      {
        "label": "Sizes available",
        "value": "6"
      },
      {
        "label": "Size range",
        "value": "600×600 to 1200×2400 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "floor-tiles-series-c",
    "vertical": "ceramic-tiles",
    "categorySlug": "floor-tiles",
    "name": "Floor Tiles – Series C",
    "collection": "Series C",
    "shortDescription": "Floor Tiles, Series C, in 6 sizes from 600×600 to 1200×2400 mm.",
    "description": "Floor tiles for living rooms, bedrooms, lobbies and commercial spaces. Series C is offered in 6 sizes: 600×600 mm, 600×1200 mm, 800×1600 mm, 1200×1200 mm, 800×2400 mm, 1200×2400 mm.",
    "finishes": [],
    "sizes": [
      "600×600 mm",
      "600×1200 mm",
      "800×1600 mm",
      "1200×1200 mm",
      "800×2400 mm",
      "1200×2400 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Floor Tiles"
      },
      {
        "label": "Series",
        "value": "C"
      },
      {
        "label": "Sizes available",
        "value": "6"
      },
      {
        "label": "Size range",
        "value": "600×600 to 1200×2400 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "floor-tiles-series-d",
    "vertical": "ceramic-tiles",
    "categorySlug": "floor-tiles",
    "name": "Floor Tiles – Series D",
    "collection": "Series D",
    "shortDescription": "Floor Tiles, Series D, in 6 sizes from 600×600 to 1200×2400 mm.",
    "description": "Floor tiles for living rooms, bedrooms, lobbies and commercial spaces. Series D is offered in 6 sizes: 600×600 mm, 600×1200 mm, 800×1600 mm, 1200×1200 mm, 800×2400 mm, 1200×2400 mm.",
    "finishes": [],
    "sizes": [
      "600×600 mm",
      "600×1200 mm",
      "800×1600 mm",
      "1200×1200 mm",
      "800×2400 mm",
      "1200×2400 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Floor Tiles"
      },
      {
        "label": "Series",
        "value": "D"
      },
      {
        "label": "Sizes available",
        "value": "6"
      },
      {
        "label": "Size range",
        "value": "600×600 to 1200×2400 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "wall-tiles-series-a",
    "vertical": "ceramic-tiles",
    "categorySlug": "wall-tiles",
    "name": "Wall Tiles – Series A",
    "collection": "Series A",
    "shortDescription": "Wall Tiles, Series A, in 4 sizes from 300×450 to 600×1200 mm.",
    "description": "Wall tiles for feature walls, living spaces and everyday interiors. Series A is offered in 4 sizes: 300×450 mm, 300×600 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "300×450 mm",
      "300×600 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Wall Tiles"
      },
      {
        "label": "Series",
        "value": "A"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "300×450 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "wall-tiles-series-b",
    "vertical": "ceramic-tiles",
    "categorySlug": "wall-tiles",
    "name": "Wall Tiles – Series B",
    "collection": "Series B",
    "shortDescription": "Wall Tiles, Series B, in 4 sizes from 300×450 to 600×1200 mm.",
    "description": "Wall tiles for feature walls, living spaces and everyday interiors. Series B is offered in 4 sizes: 300×450 mm, 300×600 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "300×450 mm",
      "300×600 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Wall Tiles"
      },
      {
        "label": "Series",
        "value": "B"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "300×450 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "bathroom-tiles-series-a",
    "vertical": "ceramic-tiles",
    "categorySlug": "bathroom-tiles",
    "name": "Bathroom Tiles – Series A",
    "collection": "Series A",
    "shortDescription": "Bathroom Tiles, Series A, in 4 sizes from 300×600 to 700×1200 mm.",
    "description": "Tiles for bathroom floors and walls, chosen for spaces that see water every day. Series A is offered in 4 sizes: 300×600 mm, 600×600 mm, 600×1200 mm, 700×1200 mm.",
    "finishes": [],
    "sizes": [
      "300×600 mm",
      "600×600 mm",
      "600×1200 mm",
      "700×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Bathroom Tiles"
      },
      {
        "label": "Series",
        "value": "A"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "300×600 to 700×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "bathroom-tiles-series-b",
    "vertical": "ceramic-tiles",
    "categorySlug": "bathroom-tiles",
    "name": "Bathroom Tiles – Series B",
    "collection": "Series B",
    "shortDescription": "Bathroom Tiles, Series B, in 4 sizes from 300×600 to 700×1200 mm.",
    "description": "Tiles for bathroom floors and walls, chosen for spaces that see water every day. Series B is offered in 4 sizes: 300×600 mm, 600×600 mm, 600×1200 mm, 700×1200 mm.",
    "finishes": [],
    "sizes": [
      "300×600 mm",
      "600×600 mm",
      "600×1200 mm",
      "700×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Bathroom Tiles"
      },
      {
        "label": "Series",
        "value": "B"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "300×600 to 700×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "bathroom-tiles-series-c",
    "vertical": "ceramic-tiles",
    "categorySlug": "bathroom-tiles",
    "name": "Bathroom Tiles – Series C",
    "collection": "Series C",
    "shortDescription": "Bathroom Tiles, Series C, in 4 sizes from 300×600 to 700×1200 mm.",
    "description": "Tiles for bathroom floors and walls, chosen for spaces that see water every day. Series C is offered in 4 sizes: 300×600 mm, 600×600 mm, 600×1200 mm, 700×1200 mm.",
    "finishes": [],
    "sizes": [
      "300×600 mm",
      "600×600 mm",
      "600×1200 mm",
      "700×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Bathroom Tiles"
      },
      {
        "label": "Series",
        "value": "C"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "300×600 to 700×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "kitchen-tiles-series-a",
    "vertical": "ceramic-tiles",
    "categorySlug": "kitchen-tiles",
    "name": "Kitchen Tiles – Series A",
    "collection": "Series A",
    "shortDescription": "Kitchen Tiles, Series A, in 4 sizes from 300×450 to 600×1200 mm.",
    "description": "Tiles for kitchen walls, backsplashes and work areas that are easy to keep clean. Series A is offered in 4 sizes: 300×450 mm, 300×600 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "300×450 mm",
      "300×600 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Kitchen Tiles"
      },
      {
        "label": "Series",
        "value": "A"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "300×450 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "kitchen-tiles-series-b",
    "vertical": "ceramic-tiles",
    "categorySlug": "kitchen-tiles",
    "name": "Kitchen Tiles – Series B",
    "collection": "Series B",
    "shortDescription": "Kitchen Tiles, Series B, in 4 sizes from 300×450 to 600×1200 mm.",
    "description": "Tiles for kitchen walls, backsplashes and work areas that are easy to keep clean. Series B is offered in 4 sizes: 300×450 mm, 300×600 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "300×450 mm",
      "300×600 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Kitchen Tiles"
      },
      {
        "label": "Series",
        "value": "B"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "300×450 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "outdoor-tiles-all-sizes",
    "vertical": "ceramic-tiles",
    "categorySlug": "outdoor-tiles",
    "name": "Outdoor Tiles",
    "collection": "All Sizes Series",
    "shortDescription": "Outdoor Tiles, All Sizes Series, in 14 sizes from 300×450 to 1600×3200 mm.",
    "description": "Tiles for terraces, balconies, pathways and other outdoor areas. All Sizes Series is offered in 14 sizes: 300×450 mm, 300×500 mm, 400×400 mm, 300×600 mm, 700×300 mm, 600×600 mm, 800×800 mm, 600×1200 mm, 700×1200 mm, 800×1600 mm, 800×2000 mm, 800×2400 mm, 1700×1500 mm, 1600×3200 mm.",
    "finishes": [],
    "sizes": [
      "300×450 mm",
      "300×500 mm",
      "400×400 mm",
      "300×600 mm",
      "700×300 mm",
      "600×600 mm",
      "800×800 mm",
      "600×1200 mm",
      "700×1200 mm",
      "800×1600 mm",
      "800×2000 mm",
      "800×2400 mm",
      "1700×1500 mm",
      "1600×3200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Outdoor Tiles"
      },
      {
        "label": "Series",
        "value": "All sizes"
      },
      {
        "label": "Sizes available",
        "value": "14"
      },
      {
        "label": "Size range",
        "value": "300×450 to 1600×3200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "ceramic-tiles-series-e",
    "vertical": "ceramic-tiles",
    "categorySlug": "ceramic-tiles",
    "name": "Ceramic Tiles",
    "collection": "Series E",
    "shortDescription": "Ceramic Tiles, Series E, in 4 sizes from 400×400 to 600×1200 mm.",
    "description": "Ceramic tiles for residential floors and walls. Series E is offered in 4 sizes: 400×400 mm, 500×500 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "400×400 mm",
      "500×500 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Ceramic Tiles"
      },
      {
        "label": "Series",
        "value": "E"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "400×400 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "vitrified-tiles-series-e",
    "vertical": "ceramic-tiles",
    "categorySlug": "vitrified-tiles",
    "name": "Vitrified Tiles",
    "collection": "Series E",
    "shortDescription": "Vitrified Tiles, Series E, in 4 sizes from 400×400 to 600×1200 mm.",
    "description": "Vitrified tiles for floors in homes, offices and commercial spaces. Series E is offered in 4 sizes: 400×400 mm, 500×500 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "400×400 mm",
      "500×500 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Vitrified Tiles"
      },
      {
        "label": "Series",
        "value": "E"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "400×400 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "dc-tiles-series-e",
    "vertical": "ceramic-tiles",
    "categorySlug": "dc-tiles",
    "name": "D.C. Tiles",
    "collection": "Series E",
    "shortDescription": "D.C. Tiles, Series E, in 4 sizes from 400×400 to 600×1200 mm.",
    "description": "D.C. (double-charge) tiles for floors in homes and busy commercial spaces. Series E is offered in 4 sizes: 400×400 mm, 500×500 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "400×400 mm",
      "500×500 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "D.C. Tiles"
      },
      {
        "label": "Series",
        "value": "E"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "400×400 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "nano-tiles-series-e",
    "vertical": "ceramic-tiles",
    "categorySlug": "nano-tiles",
    "name": "Nano Tiles",
    "collection": "Series E",
    "shortDescription": "Nano Tiles, Series E, in 4 sizes from 400×400 to 600×1200 mm.",
    "description": "Nano-finish tiles for floors in homes, showrooms and retail spaces. Series E is offered in 4 sizes: 400×400 mm, 500×500 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "400×400 mm",
      "500×500 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Nano Tiles"
      },
      {
        "label": "Series",
        "value": "E"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "400×400 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  },
  {
    "slug": "parking-tiles-series-e",
    "vertical": "ceramic-tiles",
    "categorySlug": "parking-tiles",
    "name": "Parking Tiles",
    "collection": "Series E",
    "shortDescription": "Parking Tiles, Series E, in 4 sizes from 400×400 to 600×1200 mm.",
    "description": "Tiles for parking areas, driveways and other spaces that take vehicle traffic. Series E is offered in 4 sizes: 400×400 mm, 500×500 mm, 600×600 mm, 600×1200 mm.",
    "finishes": [],
    "sizes": [
      "400×400 mm",
      "500×500 mm",
      "600×600 mm",
      "600×1200 mm"
    ],
    "specs": [
      {
        "label": "Category",
        "value": "Parking Tiles"
      },
      {
        "label": "Series",
        "value": "E"
      },
      {
        "label": "Sizes available",
        "value": "4"
      },
      {
        "label": "Size range",
        "value": "400×400 to 600×1200 mm"
      }
    ],
    "tags": [],
    "tone": "tile",
    "syncOnSeed": true
  }
];
